language: python
python:
  - "3.6"

env:
  - DARTSENSE_SESSION_SECRET=deadbeef
  - DARTSENSE_HOST=localhost
  - DARTSENSE_USERNAME=travis
  - DARTSENSE_PASSWORD=""
  - DARTSENSE_SCHEMA=dartsense_test
  - DARTSENSE_GOOGLE_ID="deadbeef"
  - DARTSENSE_GOOGLE_SECRET="deadbeef"

install:
  - mysql -uroot -e 'create database dartsense_test'
  - mysql -uroot dartsense_test < share/db/db.sql
  - pip install -r requirements.txt

script: 
  - pytest --cov=dartsense

after_success:
  - coveralls

